import java.util.Random;
import java.util.Scanner;

/**
 * Description : Lab3, has methods that can be used to play games!
 * author : Shriyash
 * since : 0324/2025
 */


public class Main {

    static Scanner scanner = new Scanner(System.in);
    static Random random = new Random();

    /**
     * Description : Main menu used to navigate & call through different methods in the Main class.
     * @param args : null, nothing is passed!
     * @return: N/A
     */
    public static void main(String[] args) {
        System.out.println("Choose the game you want to play 1. Guessing Game, 2. Rock-Paper-Scissors, 3.Exit");

        int user_Choice = scanner.nextInt();
        if(user_Choice == 1){
            guess_Game();
        }else if(user_Choice ==2){
            rpc_Game();
        }

    }


    /**
     * Description : A guess game procedure where the user guesses the number generated by this function.
     * parameters : N/A
     * return : N/A
     */
    public static void guess_Game(){

        int tries = 5;
        System.out.println("I'm thinking of a number between 1-150");
        System.out.println("guess what it is?, you get 5 tries");

        int computer_random = random.nextInt(101);
        for(int i = tries; i > 0; i--){
            int user_try = scanner.nextInt();
            if(user_try == computer_random){
                System.out.println("Good Guess, you guessed right!");
            }else if(user_try<computer_random){
                System.out.println("Guess higher ;)");
            }else{
                System.out.println("Guess lower ;)");
            }
        }

        System.out.println("Nice try, you are out of tries for now, the correct number was " + computer_random);
        System.out.println("Would you like to play again?, y/n");
        String user_try_again  = scanner.next();
        if(user_try_again.toLowerCase().equals("y")){
            guess_Game();
        }
        Main.main(null);
    }

    /**
     * Description : Rock paper scissors game wih the computer using Random object
     * parameters :  N/A
     * return : N/A
     */
    public static void rpc_Game(){

        System.out.println("Enter your choice 1. Rock, 2. Paper., 3. Scissors");
        int computer_Choice = random.nextInt(3) +1 ;
        int user_Choice = scanner.nextInt();

        if(computer_Choice == user_Choice ){
            System.out.println("It is a tie");
        }else if(computer_Choice == 1 && user_Choice == 3){
            System.out.println("You lose !");
        }else if(computer_Choice == 2  && user_Choice == 1){
            System.out.println("You lose");
        }else if(computer_Choice == 3 && user_Choice == 2 ){
            System.out.println("You lose");
        }else{
            System.out.println("You win");
        }
        System.out.println("Computer Choice: " +computer_Choice);

        System.out.println("Would you like to play again?, y/n");
        String user_try_again  = scanner.next();
        if(user_try_again.toLowerCase().equals("y")){
            rpc_Game();
        }
        Main.main(null);

    }



}