import java.util.Random;
import java.util.Scanner;

/**
 * Description : Lab3, has methods that can be used to play games!
 * author : Shriyash
 * since : 0324/2025
 */


public class Main {

    static Scanner scanner = new Scanner(System.in);
    public static void main(String[] args) {
        System.out.println("Hello, World!");

        guess_Game();
    }


    /**
     * Description : A guess game method where the user guesses the number generated by this function.
     * parameters : N/A
     * return : N/A
     */
    public static void guess_Game(){

        int tries = 5;
        System.out.println("I'm thinking of a numb3r between 1-150");
        System.out.println("guess what it is?, you get 5 tries");
        Random random = new Random();
        int computer_random = random.nextInt(101);
        for(int i = tries; i > 0; i--){
            int user_try = scanner.nextInt();
            if(user_try == computer_random){
                System.out.println("Good Guess, you guessed right!");
            }else if(user_try<computer_random){
                System.out.println("Guess higher ;)");
            }else{
                System.out.println("Guess lower ;)");
            }
        }

        System.out.println("Nice try, you are out of tries for now, the correct number was " + computer_random);
        System.out.println("Would you like to play again?, y/n");
        String user_try_again  = scanner.next();
        if(user_try_again.toLowerCase().equals("y")){
            guess_Game();
        }
    }



}